export const scrapeIds = {
  lp: {
    hero: "hero",
    programs: "programs",
    pricing: "pricing",
    trainers: "trainers",
    access: "access",
    faq: "faq",
    reservationCta: "reservation-cta",
  },
  reservation: {
    prefectureSelect: "prefecture-select",
    storeList: "store-list",
    storeCard: "store-card",
    availabilityCalendar: "availability-calendar",
    previousWeekButton: "calendar-previous-week",
    nextWeekButton: "calendar-next-week",
    availableSlot: "available-slot",
    selectedSlot: "selected-slot",
    nextButton: "reservation-next-button",
  },
  form: {
    reservationForm: "reservation-form",
    customerName: "customer-name",
    customerEmail: "customer-email",
    customerPhone: "customer-phone",
    trainingGoal: "training-goal",
    customerNote: "customer-note",
    submitButton: "reservation-submit-button",
  },
  confirm: {
    page: "reservation-confirm",
    submitButton: "reservation-confirm-submit-button",
  },
  thanks: {
    page: "reservation-thanks",
    summary: "reservation-summary",
    number: "reservation-number",
  },
  admin: {
    loginForm: "admin-login-form",
    password: "admin-password",
    loginButton: "admin-login-button",
    storeList: "admin-store-list",
    storeCard: "admin-store-card",
    bookingsTable: "admin-bookings-table",
    bookingRow: "booking-row",
    bookingStore: "booking-store",
    bookingDatetime: "booking-datetime",
    bookingCustomerName: "booking-customer-name",
    bookingCustomerEmail: "booking-customer-email",
    bookingCustomerPhone: "booking-customer-phone",
  },
} as const;
